spring.application.name=transactions-service



spring.datasource.url=jdbc:postgresql://localhost:5435/${DB_NAME:smartbancs}
spring.datasource.username=${DB_USER:smartbancs}
spring.datasource.password=${DB_PASSWORD:smartbancs}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.pattern.console=%d{HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,metrics


